grafana:
  enabled: true
  fullnameOverride: grafana

  adminUser: admin
  adminPassword: "${grafana_admin_password}"

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 3d
    scrapeInterval: 30s
    evaluationInterval: 30s

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

defaultRules:
  create: true
