apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.POSTGRES_PASSWORD | quote }}
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}
