{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .repoURL | quote }}
    targetRevision: {{ .targetRevision | quote }}
    path: {{ .path | quote }}
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: {{ .destinationServer | quote }}
    namespace: {{ .namespace | quote }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
