replicaCount: 2

image:
  repository: 559292737982.dkr.ecr.us-west-2.amazonaws.com/lesson-8-9-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  POSTGRES_DB: goit_db
  POSTGRES_USER: goit_user
  POSTGRES_PASSWORD: goit_password
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
