replicaCount: 2

image:
  repository: 559292737982.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "goit_db"
  POSTGRES_USER: "goit_user"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

secret:
  SECRET_KEY: "change-me-in-production"
  POSTGRES_PASSWORD: "change-me-in-production"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  readiness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 20

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
